### ISSUE TITLE
Support for BLE WiFi Provisioning

### ISSUE THREAD

**Issue by Yoimer** [Raghav3107/amazon-freertos-workspace-v202012#1]
Hello there. Congratulations for this work you have made. I am going to pull and compile this.
Quick question. Do you plan to incorporate BLE on this? I know that for now we have to hard code the SSID and Password. But for a practical and production environment this needs to use BLE. Currently, the official FreeRTOS demos provide the SDK for BLE in both Android and IOS.
Looking forward to hearing from you soon.
Thanks in advance.

**Comment by Raghav3107** [comment]
I m working on it. I got some linking issue on that. So, I create the issue on the amazon-freertos repository. You can check it [here](https://github.com/aws/amazon-freertos/issues/3169).

**Comment by Yoimer** [comment]
@Raghav3107 Thanks for replying. Looking forward to seeing their reply.

A piece on advice, remove your own AWS credentials from the repository (AWS IoT Thing and Certificates). If those are still active, anyone can pull your code, compile and make use of them.

It is a good practice not to publish personal data (credentials) on public repositories.

Have a great week ahead.

**Comment by Raghav3107** [comment]
> A piece on advice, remove your own AWS credentials from the repository (AWS IoT Thing and Certificates). If those are still active, anyone can pull your code, compile and make use of them.

Thanks, @Yoimer for your concern.
I removed the AWS credentials yesterday.

**Comment by Raghav3107** [comment]
Hello @Yoimer 
Sorry I cannot pull the BLE codes here.
If you want I can guide how you to add ble for SSID and Password.

**Comment by Yoimer** [comment]
@Raghav3107 Hello. I know how to add BLE WiFi Provisioning on the demos from AWS FreeRTOS. Thanks

**Comment by Raghav3107** [comment]
Okay @Yoimer .

Did you added the BLE WiFi provisional in this same repository?

**Comment by Yoimer** [comment]
@Raghav3107 Nope. I just used that configuration in the past when I was developing in a private repository I have here.

**Comment by Yoimer** [comment]
@Raghav3107 Does this repository handle  mqtt, device shadows and otas?

**Comment by Raghav3107** [comment]
OTA is not working in this repo.
I created ticket on freertos repository. You can check it there.
