### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by smartnimbus** [Raghav3107/amazon-freertos-workspace-v202012#2]
HI Raghav
Was looking for some examples on freertos OTA and came across your code. 
can you please contact me on amit.p.patel@hotmail.co.uk
Regards
Amit

**Comment by Raghav3107** [comment]
Hello @smartnimbus 
I will very happy to help you. 
But I m very new to freertos OTA. I have some basic knowledge of the freertos OTA library.
It will be best If you create an issue on [amazon-freertos](https://github.com/aws/amazon-freertos) and [Freertos](https://github.com/FreeRTOS) repository.

**Comment by smartnimbus** [comment]
HI Raghav

Did you get the OTA working on the ESP32?

Regards
Amit

**Comment by Raghav3107** [comment]
No. OTA is not working as of now. I created the issue on Freertos
coremQTT-Agent repository.
Waiting for their response.

**Comment by smartnimbus** [comment]
the ota_pal.c is for windows was not sure if that was causing the issue 
329 8348 [OTAAgentTask] [INFO] [OTA] [ota.c:1645] 330 8348 [OTAAgentTask] Extracted parameter: [key: value]=[execution.jobId: AFR_OTA-AFR_test_3]331 8348 [OTAAgentTask]
332 8349 [OTAAgentTask] [INFO] [OTA] [ota.c:1645] 333 8349 [OTAAgentTask] Extracted parameter: [key: value]=[execution.jobDocument.afr_ota.streamname: AFR_OTA-876e8da6-c453-412c-90a0-c3ed839977b1]334 8350 [OTAAgentTask]
335 8351 [OTAAgentTask] [INFO] [OTA] [ota.c:1645] 336 8351 [OTAAgentTask] Extracted parameter: [key: value]=[execution.jobDocument.afr_ota.protocols: ["MQTT"]]337 8352 [OTAAgentTask]
338 8352 [OTAAgentTask] [INFO] [OTA] [ota.c:1645] 339 8352 [OTAAgentTask] Extracted parameter: [key: value]=[filepath: /]340 8352 [OTAAgentTask]
341 8354 [OTAAgentTask] [INFO] [OTA] [ota.c:1684] 342 8354 [OTAAgentTask] Extracted parameter: [key: value]=[filesize: 910608]343 8354 [OTAAgentTask]
344 8355 [OTAAgentTask] [INFO] [OTA] [ota.c:1684] 345 8355 [OTAAgentTask] Extracted parameter: [key: value]=[fileid: 0]346 8355 [OTAAgentTask]
347 8356 [OTAAgentTask] [INFO] [OTA] [ota.c:1645] 348 8356 [OTAAgentTask] Extracted parameter: [key: value]=[certfile: /]349 8356 [OTAAgentTask]
350 8358 [OTAAgentTask] [INFO] [OTA] [ota.c:1575] 351 8358 [OTAAgentTask] Extracted parameter [ sig-sha256-ecdsa: MEQCICPK6GmYmWaGsx5gdrsc7Ev6fKW4... ]352 8359 [OTAAgentTask]
353 8359 [OTAAgentTask] [INFO] [OTA] [ota.c:2199] 354 8359 [OTAAgentTask] Job document was accepted. Attempting to begin the update.355 8360 [OTAAgentTask]
356 8360 [OTAAgentTask] [INFO] [OTA] [ota.c:2323] 357 8360 [OTAAgentTask] Job parsing success: OtaJobParseErr_t=OtaJobParseErrNone, Job name=AFR_OTA-AFR_test_3358 8362 [OTAAgentTask]
359 8362 [OTAAgentTask] [WARN] [OTA] [ota_over_mqtt_demo.c:567] 360 8362 [OTAAgentTask] Received an unhandled callback event from OTA Agent, event = (6)

361 8363 [OTAAgentTask]
362 8364 [OTAAgentTask] [ERROR] [OTA] [ota_pal.c:85] 363 8364 [OTAAgentTask] ERROR - Failed to start operation: already active!
364 8365 [OTAAgentTask]
365 8365 [OTAAgentTask] [ERROR] [OTA] [ota_pal.c:495] 366 8365 [OTAAgentTask] Unable to open image state file.
367 8366 [OTAAgentTask]
368 8428 [main] [WARN] [DEMO] [mqtt_connection_manager.c:643] 369 8428 [OTAAgentTask] [INFO] [OTA] [ota_over_mqtt_demo.c:876] 370 8428 [main] WARN:  Received an unsolicited publish from topic $aws/things/NOD03-01-40f5205ba244/jobs/AFR_OTA-AFR_test_3/update/accepted371 8429 [OTAAgentTask] Sent PUBLISH packet to broker $aws/things/NOD03-01-40f5205ba244/jobs/AFR_OTA-AFR_test_3/update to broker.

372 8430 [main]
373 8430 [OTAAgentTask]
374 8431 [OTAAgentTask] [INFO] [OTA] [ota.c:2839] 375 8431 [OTAAgentTask] Current State=[WaitingForJob], Event=[ReceivedJobDocument], New state=[CreatingFile]376 8432 [OTA-Task] [INFO] [OTA] [ota_over_mqtt_demo.c:1099] 377 8432 [OTA-Task]  Received: 0   Queued: 0   Processed: 0   Dropped: 0

**Comment by Raghav3107** [comment]
No. OTA is not working as of now. I created the issue on Freertos coremQTT-Agent repository.
Waiting for their response. You can check that issue [here](https://github.com/FreeRTOS/coreMQTT-Agent-Demos/issues/52)

**Comment by smartnimbus** [comment]
cool let me know if you manage to resolve it. if i manage to resolve it i will update you here. my email is above.
have fun. thank you

**Comment by Raghav3107** [comment]
Ok, I will inform you if resolve the issue.

**Comment by smartnimbus** [comment]
HI Raghav
you can get the ESP 32 ota_pal from 
https://github.com/aws/amazon-freertos/tree/feature/ota_v3_integration/vendors/espressif/boards/ports/ota_pal_for_aws
this will be easy if can communicate over email :)

**Comment by Raghav3107** [comment]
okay. You can contact me at `raghavjha1531@gmail.com. `
Did you try with this ota_pal?

**Comment by Raghav3107** [comment]
Hello @smartnimbus 
You can check the new repository -> [https://github.com/Raghav3107/amazon-freertos-custom-v202107](https://github.com/Raghav3107/amazon-freertos-custom-v202107) there I tested the OTA, MQTT and Shadow together.

Hope this will you!

Regards,
Raghav

**Comment by smartnimbus** [comment]
HI Raghav 
Thank you for the update I will give it a go.

Regards
Amit
